Blog.WebUI/Models/ReviewListViewModel.cs
using Blog.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.WebUI.Models
{
    public class ReviewListViewModel
    {
        public IEnumerable<Review> Reviews { get; set; }
        public Review Review { get; set; }
    }
}

Blog.WebUI/Models/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.WebUI.Models
{
    public class ReviewViewModel
    {
       public string Author { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }

    }
}

Blog.WebUI/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.WebUI.Models
{
    public class UserViewModel
    {
    }
}

Blog.WebUI/Controllers/GuestController.cs
using Blog.Domain.Concrete;
using Blog.Domain.Entities;
using Blog.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.WebUI.Controllers
{
    public class GuestController : Controller
    {
        UnitOfWork unitOfWork;

        public GuestController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Guest
        public ActionResult Index()
        {
            var reviews = unitOfWork.Reviews.FindAll();
            ReviewListViewModel model = new ReviewListViewModel();
            model.Reviews = reviews;
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Review review)
        {
            unitOfWork.Reviews.Create(review);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }



        
    }
}

Blog.WebUI/Controllers/HomeController.cs
using Blog.Domain.Concrete;
using Blog.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.WebUI.Controllers
{
    public class HomeController : Controller
    {
        UnitOfWork unit;

        public HomeController()
        {
            unit = new UnitOfWork();
        }

        public ActionResult Index()
        {
            List<Article> articles = unit.Articles.FindAll().ToList();

            return View(articles);
        }

       
    }
}

Blog.WebUI/Controllers/ProfileController.cs
using Blog.Domain.Concrete;
using Blog.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.WebUI.Controllers
{
    public class ProfileController : Controller
    {
        UnitOfWork unitOfWork;
        public ProfileController()
        {
            unitOfWork = new UnitOfWork();
        }
        public ActionResult Index()
        {
            ViewBag.Genders = new string[] { "Мужской", "Женский" };
            ViewBag.Languages = new string[] { "English", "Українська", "Русский", "Deutsch", "Other" };
            return View();
        }
        [HttpGet]
        public ActionResult ProfileResult()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ProfileResult(User user, List<string> languages)
            {
            if (languages==null)
            {
                languages = new List<string>();
            }
            user.Languages = languages;
            if (ModelState.IsValid)
            {
                unitOfWork.Roles.Create(user);
                unitOfWork.Save();
                return View(user);
            }
                return View("Index");
        }
    }
}

Blog.WebUI/Views/Guest/Index.cshtml
@model Blog.WebUI.Models.ReviewListViewModel
@{
    ViewBag.Title = "Reviews";
}

<h2>Reviews</h2>

<section class="reviews">
    @foreach (var item in Model.Reviews)
    {
        <div class="card card-review">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2">
                        <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid" />
                        <p class="text-secondary text-center">@item.Date.ToShortDateString()</p>
                    </div>
                    <div class="col-md-10">
                        <a class="float-left"><strong>@item.Author</strong> </a>
                        <div class="clearfix"></div>
                        <p>@item.Text</p>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

<section class="register-form">
    <h3>Add review</h3>
    @using (Html.BeginForm("Add", "Guest", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Review.ReviewId)
        <div class="form-group">
            @Html.LabelFor(m => m.Review.Author, "Name")
            @Html.TextBoxFor(m => m.Review.Author, new { @class = "form-control", @placeholder = "Enter your name", @pattern = "^[a-zA-ZА-я0-9ЁёІіЇїЄє]+$", required = "required" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Review.Text, "Review")
            @Html.TextAreaFor(m => m.Review.Text, new { @class = "form-control", @placeholder = "Enter review text", @rows = "4", required = "required"})
        </div>

        <input type="submit" class="btn btn-dark btn-add" value="Add" />
    }
</section>

Blog.WebUI/Views/Home/Index.cshtml
@model List<Blog.Domain.Entities.Article>
@{
    ViewBag.Title = "Home Page";
}


<h1>Home</h1>
<section class="articles">
    @foreach (var item in Model)
    {
        <article class="card article-preview">
            <div class="card-body ">
                <h4 class="card-title">@item.Name</h4>
                <p class="card-text">@item.Text</p>
                <a href="#" class="card-link">Card link</a>
            </div>
            <div class="card-footer">
                <p class="card-text"> @item.Date.ToShortDateString()</p>
            </div>
        </article>
    }

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>

    <article class="card article-preview">
        <div class="card-body ">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet volutpat consequat mauris nunc congue. Dapibus ultrices in iaculis nunc sed augue lacus viverra.
            </p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </article>
</section>

Blog.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header id="topSection">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" href="/Home/Index"><img src="~/Content/Images/blog.png" height="30"/></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Guest/Index">Guest</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Profile/Index">Profile</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <div class="container-fluid main ">
            <div class="row">
                <section class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10 " >
                @RenderBody()
                </section>
                <section class="col-md-2 col-lg-2 col-xl-2">
                    <aside>
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="/Home/Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Guest/Index">Guest</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Profile/Index">Profile</a>
                            </li>
                        </ul>
                    </aside>
                </section>
            </div>
        </div>
    </main>



    <footer class="page-footer font-small text-light bg-dark  ">
        <a id="back-to-top" href="#" class="btn btn-dark btn-lg back-to-top" role="button">
            <img src="~/Content/Images/arrow.png" width="45"/></a>

        <div class="footer-copyright text-center py-3">
            © 2020 Copyright:
            <a> Yevhenii Bas</a>

        </div>
        <!-- Copyright -->

    </footer>



    @*
        <li></li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/backToTop.js"></script>
</body>
</html>